export { setupStore } from '@/config/modules/store'
export { setupI18n } from '@/config/modules/i18n'
export { setupRouter } from '@/config/modules/router'
export { setupElementPlus } from '@/config/modules/ElementPlus'
export { setupPrimeVue } from '@/config/modules/PrimeVue'
export { setupPowerBy } from '@/config/modules/PowerBy'
export { setupFloatingVue } from '@/config/modules/FloatingVue'
