name: docker build and push

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: hiifong/mojito
          token: ${{ secrets.GH_PAT }}
          path: mojito
          submodules: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git-tag-gpgsign: true
          workdir: mojito
      - name: Update Mojito
        run: |
          git config --global user.name "hiifong"
          git config --global user.email "i@hiif.ong"
          cd mojito
          cd ui
          git fetch
          git checkout release/v0.1.0
          git merge
          cd ..
          git add ui
          git commit -S -m "Update UI"
          git push origin main